<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="humanoid_xacro">

  <!-- Include macros -->
  <xacro:include filename="$(find humanoid_description)/urdf/macros/inertia.xacro"/>
  <xacro:include filename="$(find humanoid_description)/urdf/macros/leg.xacro"/>

  <!-- ========== PROPERTIES ========== -->
  <xacro:property name="leg_hip_length" value="0.3"/>
  <xacro:property name="leg_knee_length" value="0.3"/>
  <xacro:property name="leg_foot_length" value="0.15"/>
  <xacro:property name="leg_foot_width" value="0.08"/>
  <xacro:property name="leg_hip_mass" value="3.0"/>
  <xacro:property name="leg_knee_mass" value="2.0"/>
  <xacro:property name="leg_foot_mass" value="1.0"/>
  <xacro:property name="leg_radius" value="0.04"/>

  <xacro:property name="arm_shoulder_length" value="0.24"/>
  <xacro:property name="arm_elbow_length" value="0.2"/>
  <xacro:property name="arm_shoulder_mass" value="1.5"/>
  <xacro:property name="arm_elbow_mass" value="1.0"/>
  <xacro:property name="arm_radius" value="0.03"/>

  <!-- ========== TORSO (BASE LINK) ========== -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.3 0.2 0.4"/>
      </geometry>
      <material name="torso_blue">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.3 0.2 0.4"/>
      </geometry>
    </collision>
    <xacro:box_inertia mass="15.0" x="0.3" y="0.2" z="0.4" xyz="0 0 0"/>
  </link>

  <!-- ========== HEAD ========== -->
  <link name="head">
    <visual>
      <geometry>
        <sphere radius="0.12"/>
      </geometry>
      <material name="head_gray">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.12"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia mass="2.0" radius="0.12"/>
  </link>

  <joint name="neck_joint" type="revolute">
    <parent link="base_link"/>
    <child link="head"/>
    <origin xyz="0 0 0.25" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.785" upper="0.785" effort="10.0" velocity="2.0"/>
    <dynamics damping="0.5" friction="0.1"/>
  </joint>

  <!-- ========== INSTANTIATE LEGS ========== -->
  <xacro:leg prefix="left" reflect="1">
    <origin xyz="0 0.1 -0.2" rpy="0 0 0"/>
  </xacro:leg>

  <xacro:leg prefix="right" reflect="-1">
    <origin xyz="0 -0.1 -0.2" rpy="0 0 0"/>
  </xacro:leg>

  <!-- ========== LEFT ARM ========== -->
  <link name="left_shoulder">
    <visual>
      <origin xyz="0 0 ${-arm_shoulder_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_shoulder_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="arm_gray">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${-arm_shoulder_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_shoulder_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="${arm_shoulder_mass}"
                            radius="${arm_radius}"
                            length="${arm_shoulder_length}"
                            xyz="0 0 ${-arm_shoulder_length/2}"/>
  </link>

  <joint name="left_shoulder_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_shoulder"/>
    <origin xyz="0 0.15 0.15" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="80.0" velocity="2.5"/>
    <dynamics damping="0.5" friction="0.1"/>
  </joint>

  <link name="left_elbow">
    <visual>
      <origin xyz="0 0 ${-arm_elbow_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_elbow_length}" radius="${arm_radius * 0.85}"/>
      </geometry>
      <material name="arm_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-arm_elbow_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_elbow_length}" radius="${arm_radius * 0.85}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="${arm_elbow_mass}"
                            radius="${arm_radius * 0.85}"
                            length="${arm_elbow_length}"
                            xyz="0 0 ${-arm_elbow_length/2}"/>
  </link>

  <joint name="left_elbow_joint" type="revolute">
    <parent link="left_shoulder"/>
    <child link="left_elbow"/>
    <origin xyz="0 0 ${-arm_shoulder_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0.0" upper="2.356" effort="60.0" velocity="2.5"/>
    <dynamics damping="0.3" friction="0.05"/>
  </joint>

  <!-- ========== RIGHT ARM (SYMMETRIC) ========== -->
  <link name="right_shoulder">
    <visual>
      <origin xyz="0 0 ${-arm_shoulder_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_shoulder_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="arm_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-arm_shoulder_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_shoulder_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="${arm_shoulder_mass}"
                            radius="${arm_radius}"
                            length="${arm_shoulder_length}"
                            xyz="0 0 ${-arm_shoulder_length/2}"/>
  </link>

  <joint name="right_shoulder_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_shoulder"/>
    <origin xyz="0 -0.15 0.15" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="80.0" velocity="2.5"/>
    <dynamics damping="0.5" friction="0.1"/>
  </joint>

  <link name="right_elbow">
    <visual>
      <origin xyz="0 0 ${-arm_elbow_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_elbow_length}" radius="${arm_radius * 0.85}"/>
      </geometry>
      <material name="arm_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-arm_elbow_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_elbow_length}" radius="${arm_radius * 0.85}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="${arm_elbow_mass}"
                            radius="${arm_radius * 0.85}"
                            length="${arm_elbow_length}"
                            xyz="0 0 ${-arm_elbow_length/2}"/>
  </link>

  <joint name="right_elbow_joint" type="revolute">
    <parent link="right_shoulder"/>
    <child link="right_elbow"/>
    <origin xyz="0 0 ${-arm_shoulder_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0.0" upper="2.356" effort="60.0" velocity="2.5"/>
    <dynamics damping="0.3" friction="0.05"/>
  </joint>

</robot>
