<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="leg" params="prefix reflect *origin">

    <!-- Hip Link -->
    <link name="${prefix}_hip">
      <visual>
        <origin xyz="0 0 ${-leg_hip_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${leg_hip_length}" radius="${leg_radius}"/>
        </geometry>
        <material name="leg_gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${-leg_hip_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${leg_hip_length}" radius="${leg_radius}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia mass="${leg_hip_mass}"
                              radius="${leg_radius}"
                              length="${leg_hip_length}"
                              xyz="0 0 ${-leg_hip_length/2}"/>
    </link>

    <joint name="${prefix}_hip_joint" type="revolute">
      <xacro:insert_block name="origin"/>
      <parent link="base_link"/>
      <child link="${prefix}_hip"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="150.0" velocity="3.0"/>
      <dynamics damping="1.0" friction="0.2"/>
    </joint>

    <!-- Knee Link -->
    <link name="${prefix}_knee">
      <visual>
        <origin xyz="0 0 ${-leg_knee_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${leg_knee_length}" radius="${leg_radius * 0.9}"/>
        </geometry>
        <material name="leg_gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-leg_knee_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${leg_knee_length}" radius="${leg_radius * 0.9}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia mass="${leg_knee_mass}"
                              radius="${leg_radius * 0.9}"
                              length="${leg_knee_length}"
                              xyz="0 0 ${-leg_knee_length/2}"/>
    </link>

    <joint name="${prefix}_knee_joint" type="revolute">
      <parent link="${prefix}_hip"/>
      <child link="${prefix}_knee"/>
      <origin xyz="0 0 ${-leg_hip_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="0.0" upper="2.356" effort="150.0" velocity="3.0"/>
      <dynamics damping="1.0" friction="0.2"/>
    </joint>

    <!-- Ankle/Foot -->
    <link name="${prefix}_foot">
      <visual>
        <origin xyz="${leg_foot_length/2} 0 -0.025" rpy="0 0 0"/>
        <geometry>
          <box size="${leg_foot_length} ${leg_foot_width} 0.05"/>
        </geometry>
        <material name="foot_black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${leg_foot_length/2} 0 -0.025" rpy="0 0 0"/>
        <geometry>
          <box size="${leg_foot_length} ${leg_foot_width} 0.05"/>
        </geometry>
      </collision>
      <xacro:box_inertia mass="${leg_foot_mass}"
                         x="${leg_foot_length}" y="${leg_foot_width}" z="0.05"
                         xyz="${leg_foot_length/2} 0 -0.025"/>
    </link>

    <joint name="${prefix}_ankle_joint" type="revolute">
      <parent link="${prefix}_knee"/>
      <child link="${prefix}_foot"/>
      <origin xyz="0 0 ${-leg_knee_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.785" upper="0.785" effort="100.0" velocity="2.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

  </xacro:macro>

</robot>
